<?php

namespace ClassBundle\Repository;

/**
 * SpeakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerRepository extends \Doctrine\ORM\EntityRepository
{
}
